name: duckietownrl
channels:
    - pytorch
    - defaults
dependencies:
    - python=3.8
    - pip    
    - pytorch
    - torchvision
    - numpy=1.21
    - pip:
        - gym
        - opencv-python
        - duckietown-world-daffy
        - carnivalmirror
        - pyglet==1.5.27
        - zuper-commons-z6==6.2.4
        - zmq
        - wandb
        - -e .
